/**
 * FormalDefinitionModal — Displays the formal mathematical definition of the
 * current automaton (e.g. the 5-tuple for a DFA) in a copyable text block.
 *
 * The definition string is generated by the engine's `graph.toString()` method
 * and passed in as a prop.  The modal provides a "Copy to Clipboard" button
 * with a brief "✓ Copied!" confirmation state.
 */

import type { FunctionComponent } from "react";
import { useState } from "react";

import { CloseIcon } from "./icons";

interface FormalDefinitionModalProps {
  readonly open: boolean;
  /** Optional custom title (defaults to "Formal Definition"). */
  readonly title?: string;
  /** The formal definition text to display (empty string when unavailable). */
  readonly graphString: string;
  readonly onClose: () => void;
}

export const FormalDefinitionModal: FunctionComponent<FormalDefinitionModalProps> = ({
  open,
  title = "Formal Definition",
  graphString,
  onClose,
}) => {
  const [copied, setCopied] = useState(false);

  if (!open) return null;

  const handleCopy = () => {
    if (!graphString) return;
    void navigator.clipboard.writeText(graphString);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-[9999] flex items-center justify-center">
      {/* eslint-disable-next-line jsx-a11y/click-events-have-key-events, jsx-a11y/no-static-element-interactions */}
      <div className="absolute inset-0 bg-black/40 backdrop-blur-sm" onClick={onClose} />
      <div className="relative mx-4 w-full max-w-lg animate-[fade-in_150ms_ease-out] rounded-xl border border-zinc-300 bg-zinc-50 p-6 shadow-2xl dark:border-zinc-600 dark:bg-zinc-900">
        {/* Header */}
        <div className="mb-4 flex items-center justify-between">
          <h3 className="text-base font-semibold text-zinc-900 dark:text-zinc-100">{title}</h3>
          <button
            onClick={onClose}
            className="cursor-pointer rounded-lg p-1 text-zinc-600 hover:bg-zinc-300/60 dark:text-zinc-300 dark:hover:bg-zinc-800"
          >
            <CloseIcon />
          </button>
        </div>

        {/* Definition body */}
        {graphString ? (
          <div className="max-h-[60vh] overflow-auto rounded-lg bg-zinc-100 p-4 font-mono text-[12px] leading-relaxed break-all text-zinc-800 dark:bg-zinc-800 dark:text-zinc-100">
            {graphString}
          </div>
        ) : (
          <div className="py-8 text-center text-sm text-zinc-600 dark:text-zinc-300">
            No formal definition available. Add an initial state and at least one transition.
          </div>
        )}

        {/* Copy button */}
        <div className="mt-4 flex justify-end">
          <button
            onClick={handleCopy}
            className={`cursor-pointer rounded-lg border px-4 py-2 text-sm font-medium transition-colors ${
              copied
                ? "border-green-600 bg-green-600/10 text-green-600 dark:border-green-600 dark:bg-green-600/20 dark:text-green-600"
                : "border-zinc-300 bg-white text-zinc-600 hover:bg-zinc-300/60 dark:border-zinc-600 dark:bg-zinc-900 dark:text-zinc-300 dark:hover:bg-zinc-800"
            }`}
          >
            {copied ? "✓ Copied!" : "Copy to Clipboard"}
          </button>
        </div>
      </div>
    </div>
  );
};
